spring:
  datasource:
    url: jdbc:h2:mem:dmtdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  #   url: jdbc:postgresql://dalmuti-db.cy62je3vyh4c.ap-northeast-2.rds.amazonaws.com:5424/nddmt
  #   username: postgres
  #   password: fintech204
  #   hikari:
  #     maximum-pool-size: 4

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  jpa:
    # database: POSTGRESQL
    # database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

server:
  port: 38081

logging:
  pattern:
    rolling-file-name: "${LOG_FILE}.%d{yyyyMMdd}.%i"
    console: "[%d] [%p] [%F:%M:%L] %msg%n"
    file: "[%d] [%p] [%F:%M:%L] %msg%n"
  file:
    name: /kbklog/dalmuti/app.log
    max-size: 100MB
    max-history: 365
  level:
    kbank: debug
    root: info
